#include <stdio.h>
#include <string.h>

#define MAX 100

// Function to check if a given string is in the language generated by the grammar
int cykAlgorithm(char grammar[MAX][3], int numRules, char input[MAX], int inputLength) {
    char table[MAX][MAX][MAX];
    int i, j, k, l;

    // Initialize the table
    for (i = 0; i < inputLength; i++) {
        for (j = 0; j < inputLength; j++) {
            for (k = 0; k < numRules; k++) {
                table[i][j][k] = 0;
            }
        }
    }

    // Fill in the table based on the grammar rules
    for (i = 0; i < inputLength; i++) {
        for (j = 0; j < numRules; j++) {
            if (strlen(grammar[j][1]) == 1 && grammar[j][1][0] == input[i]) {
                table[i][i][j] = 1;
            }
        }
    }

    // Perform the CYK algorithm
    for (l = 2; l <= inputLength; l++) {
        for (i = 0; i <= inputLength - l; i++) {
            j = i + l - 1;
            for (k = 0; k < numRules; k++) {
                for (int m = i; m < j; m++) {
                    if (strlen(grammar[k][1]) == 2 &&
                        table[i][m][grammar[k][1][0] - 'A'] &&
                        table[m + 1][j][grammar[k][1][1] - 'A']) {
                        table[i][j][k] = 1;
                    }
                }
            }
        }
    }

    // Check if the input string is generated by the grammar
    for (i = 0; i < numRules; i++) {
        if (table[0][inputLength - 1][i]) {
            return 1; // String is in the language
        }
    }

    return 0; // String is not in the language
}

int main() {
    char grammar[MAX][3] = {
        {"S", "AB"},
        {"A", "BA|a"},
        {"B", "CC|b"},
        {"C", "AB|a"}
    };

    char input[MAX];
    printf("Enter the input string: ");
    scanf("%s", input);

    int inputLength = strlen(input);

    if (cykAlgorithm(grammar, 4, input, inputLength)) {
        printf("The input string is in the language.\n");
    } else {
        printf("The input string is not in the language.\n");
    }

    return 0;
}
